### ISSUE TITLE
Video documentation on how to use this package.

### ISSUE THREAD

**Issue by junaidlodhi22** [Omnimind-Ltd/paypal-sdk#1]
Hi, it would be great if you can guide me on how to use this package. I have a service in my app... and now I am using PayPal WebView to allow users to make a purchase.
How can I create a product and allow users to buy that project using this package?

One more question this package uses PayPal native SDKs?

**Comment by chirag729** [comment]
Hi,
The package is a wrapper around the PayPal REST APIs documented here: https://developer.paypal.com/docs/api/overview/

At the moment it supports the 3 categories: Catalog Products, Subscriptions and Webhooks. With those three you're able to support software subscriptions but if you want your users to be able to make one off purchases for digital/physical goods you would need the Orders API: https://developer.paypal.com/docs/api/orders/v2/#orders which the package does not support at the moment.

**Comment by junaidlodhi22** [comment]
Hi, Thank you for the response. 
It would be of great help for people who are using the mentioned 3 categories.
Do you have any plans on implementing the Orders API in near future?

**Comment by chirag729** [comment]
I'm planning to implement Orders and Payouts at some point as those are the two they have implemented in their SDKs for other languages. Not sure when. If you feel up to the challenge feel free to send a pull request

**Comment by chirag729** [comment]
@junaidlodhi22 Orders API has been implemented in version 0.5.0

**Comment by goldenmommy** [comment]
is it possible to authorize payments with this package or do we need to wait until Payments API is implemented? Thanks!

**Comment by chirag729** [comment]
@goldenmommy You will need to wait until Payments API is implemented. I might get on it this month. If you're in a hurry feel free to implement and send a pull request!
