### ISSUE TITLE
it is package available payment ui?  

### ISSUE THREAD

**Issue by kindkmj** [Omnimind-Ltd/paypal-sdk#11]
or user create Ui ?

**Comment by chirag729** [comment]
You need to create a PayPal button on the PayPal website. Copy the HTML/JavaScript code provided and display that in a web view to be able to accept payments. You will get the order/subscription ID in the JavaScript callback which you can capture and use the paypal-sdk to query the status of the purchase/subscription.

**Comment by kindkmj** [comment]
oh i got it thank you 
hey this package need back-end server?

**Comment by chirag729** [comment]
You can use it for front-end although most commonly it would be used by a back-end. It is advisable you create a back-end server for saving the order ids/subscription ids for each customer.

**Comment by kindkmj** [comment]
thank you!!!
