### ISSUE TITLE
INVALID_RESOURCE_ID 

### ISSUE THREAD

**Issue by Mmisiek** [Omnimind-Ltd/paypal-sdk#12]
Hi,
I am trying to check subscription status, the token is OK but query still fails:
`2023-04-09 17:34:15.858: ERROR ApiException{statusCode: 404, error: RESOURCE_NOT_FOUND, errorDescription: The specified resource does not exist., apiError: ApiError{name: RESOURCE_NOT_FOUND, message: The specified resource does not exist., debugId: aac6a6a72220b, informationLink: null, details: [ApiErrorDetails{field: null, value: null, location: null, issue: INVALID_RESOURCE_ID, description: Requested resource ID was not found.}], links: [LinkDescription{href: https://developer.paypal.com/docs/api/v1/billing/subscriptions#RESOURCE_NOT_FOUND, rel: information_link, method: GET, encType: null}]}}`

on the sandbox website link: https://www.sandbox.paypal.com/billing/subscriptions/I-YENDFB2VSC7U works
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/4585329/230804437-d18aba39-8d58-497e-a37a-dad112cffc82.png">

What else can be wrong ?

**Comment by chirag729** [comment]
@Mmisiek Not sure. Are you setting up your sandbox environment correctly (PayPalEnvironment.sandbox) and logging in with your sandbox credentials?

**Comment by Mmisiek** [comment]
Yes I do, and I am using sandbox account credentials to get an authentication token.  On my account, I created a business sandbox account, and I am using it. Is this correct?

**Comment by Mmisiek** [comment]
You were right, my credentials to sanbox were messed up. I fixed it finally. I should write Medium article about it.
