### ISSUE TITLE
there is no "card" key/object in  "order" -> "payment_source" please change this & update plugin ASAP

### ISSUE THREAD

**Issue by Saurabhp43** [Omnimind-Ltd/paypal-sdk#13]
`"payment_source": {
        "paypal": {
            "email_address": "abcd@personal.example.com",
            "account_id": "ABCD",
            "name": {
                "given_name": "Joh",
                "surname": "Doe"
            },
            "address": {
                "country_code": "JO"
            }
        }
    },`
![Screenshot 2023-05-01 at 2 55 38 PM](https://user-images.githubusercontent.com/129053188/235434642-d2223043-7204-4a7a-aab3-a3c93cbbfec4.png)

there are no card in this object then why it call it its give me errors

**Comment by eugeniobaglieri** [comment]
Wich version resolve this issue?
Why is it marked as copleted?
