### ISSUE TITLE
How to use for "Single payment"? in flutter web

### ISSUE THREAD

**Issue by smile675** [Omnimind-Ltd/paypal-sdk#16]
Sorry if the question is silly, I am just Beginner. 
Currently, I am working on a Flutter Web Project and user need to Pay only one time payment to upgrade their link. I am doing it in php backend, using paypal_php_sdk. I am really glad to see a paypal-sdk for flutter itself. 
The subscription thing in this sdk I understood. I am not sure how to mange one time payment?

In My Project when user click a button to "Upgrade" then it open new tab where user can pay using paypal account or debit/credit card. after payment it leads to a payment success screen, if fail leads to a payment failed screen. 

I have done the whole thing using my php backend api endpoints, while doing it i had to do it like this
- after click on the button
  a http.post send to php endpoint which authorize the payment and return a url.
  from http.Response I receive the url and launch using url_launcher.
- after user complete payment in the url
   from firs php endpoint it redirect to successUrl when payment is success, in that url i secretly provide some information, so that if the success url launched i can get the information from queryParameters using go_route and use those parameter to call another php api suing http.post again. this will update the user details in database and based on this endpoint response, i show message to user what happened with their account.
   
   I think, if i can do all this thing from flutter side, the jobs will be much more easier. 
   
   Thanks

**Comment by chirag729** [comment]
@smile675  paypal-sdk is not meant for use in flutter apps itself as that would require you to store your API key in your app which is not recommended. It is meant for developers who have written their backend in Dart and want to interact with the PayPal API.

Typically a user would make a payment subscription/purchase in your app with a PayPal button. On successful purchase you get back a transaction id which you should save to your backend. This transaction id can be queried with paypal_sdk or in your case paypal_php_sdk to determine if the purchase/subscription gets cancelled at a later date.
