### ISSUE TITLE
Open paypal webView in flutter web.

### ISSUE THREAD

**Issue by DipakSkywave** [Omnimind-Ltd/paypal-sdk#3]
How to open PayPal webview in click event and how to make payment and get payment success paypal_payment_id?

**Comment by chirag729** [comment]
For subscriptions you need to create a subscription plan: https://www.paypal.com/billing/plans

Click on the menu option for the plan and select the copy code option to get the HTML for the button. 

I then use https://pub.dev/packages/webviewx package to load the HTML button in a webview. You can register a DartCallback to pass back the subscriptionId from the webview to your app.

**Comment by chirag729** [comment]
> How to open PayPal webview in click event and how to make payment and get payment success paypal_payment_id?

For subscriptions you need to create a subscription plan: https://www.paypal.com/billing/plans

Click on the menu option for the plan and select the copy code option to get the HTML for the button. 

I then use https://pub.dev/packages/webviewx package to load the HTML button in a webview. You can register a DartCallback to pass back the subscriptionId from the webview to your app.

**Comment by DipakSkywave** [comment]
> > How to open PayPal webview in click event and how to make payment and get payment success paypal_payment_id?
> 
> For subscriptions you need to create a subscription plan: https://www.paypal.com/billing/plans
> 
> Click on the menu option for the plan and select the copy code option to get the HTML for the button.
> 
> I then use https://pub.dev/packages/webviewx package to load the HTML button in a webview. You can register a DartCallback to pass back the subscriptionId from the webview to your app.

@chirag729 I can already use the https://pub.dev/packages/webviewx package but can't get success or fail call back after payment.

So, can you help me for how to get HTML payment callback in flutter web.

This is my code:

WebViewX(
          width: 1500,
          height: 600,
          initialContent: " https://api.sandbox.paypal.com/v1/payments/payment/PAYID-ABCCCCSCSCSCSCSC/execute",
          javascriptMode: JavascriptMode.unrestricted,
          initialSourceType: SourceType.url,
          onWebViewCreated: (controller) => webviewController = controller,
          // ignoreAllGestures: false,
          onWebResourceError: (error) {
          },
          onPageFinished: (value) {
          },
          navigationDelegate: (NavigationRequest request) {
            print('navigationDelegate=====>>>>   ${request}');
            return NavigationDecision.navigate;
          },
          dartCallBacks: {
            DartCallback(
                callBack: (url) {
                  print('DartCallback=====>>>>   $url');
                },
                name: 'CaptchaMessenger')
          },
        ),

Thank you in advance.

**Comment by chirag729** [comment]
@DipakSkywave 

Your initial content for WebViewX should be the actual HTML for the PayPal button. initialSourceType: SourceType.html.

When you create a subscription or product you should see a copy code option. That code is what you need to set as initial content in your webview. 

In their HTML code you should see an onApprove callback which gets triggered when the user successfully completes the purchase. You need to modify the javascript so that it triggers your dart callback to get the subscription/payment id

```
    paypal.Buttons({
        style: {
            shape: 'rect',
            color: 'gold',
            layout: 'vertical',
            label: 'subscribe'
        },
        createSubscription: function(data, actions) {
            return actions.subscription.create({
                plan_id: 'P-70R32XXXXXXXXX0MFFUAHQ'
            });
        },
        onApprove: function(data, actions) {
            SubscriptionApproved(data.subscriptionID);
        }
    }).render('#paypal-button-container-P-70R32XXXXXXXXX0MFFUAHQ');
```
