### ISSUE TITLE
Question about the purchase

### ISSUE THREAD

**Issue by rockingdice** [Omnimind-Ltd/paypal-sdk#4]
I'm trying to find an alternative way to implement the Paypal purchase, but not familiar with the REST API, I just know they are some web URLs but don't know how it works on a real phone.

My app uses a web view to make a Paypal purchase, when the user tries to pay with Paypal, the app loads a web view of the Paypal page. But on some Samsung devices, the soft keyboard is not working, so many users cannot pay. Does this package also use a web view?

When the user tries to purchase with Paypal, is this package doing the authentication work, or does the Paypal app do that? How do they input their authentication info?
Do the users need to install the Paypal app or open a webpage before the login?

Thanks for your effort in making the package!

**Comment by chirag729** [comment]
The package itself does not handle payments. It is just a wrapper around the REST API: https://developer.paypal.com/api/rest/
I have an app that uses PayPal for payments which happens through a webview however this package is not used in that front end app. It is used on the backend to verify the payment details
