### ISSUE TITLE
Capture request failure

### ISSUE THREAD

**Issue by octoreality-lab** [Omnimind-Ltd/paypal-sdk#5]
Steps to reproduce :
1- Create an order
var ordersApi = OrdersApi(payPalHttpClient);
var intent = OrderRequestIntent.capture;
AmountWithBreakdown amount = AmountWithBreakdown(currencyCode: 'EUR', value: '50.00');
var purchaseUnits = [
  PurchaseUnitRequest(amount: amount, description: 'Product example', ),
];
var orderRequest = OrderRequest(intent: intent, purchaseUnits: purchaseUnits, );
var order = await ordersApi.createOrder(orderRequest);

2- Capture a payment
var capture = await ordersApi.capturePayment(order.id!, prefer: Prefer.representation);

Expected result : the order with a new status "COMPLETED"
Actual Paypal response : "415 Unsupported Media Type" error

Solution :
File orders_api.dart:
Added Line 248 headers['Content-Type'] ??= 'application/json';
Apparently, Content-Type has to be application/json even if body is null ( Condition is in paypal_http_client.dart, line 148 )

PS : Same thing when the intent is to AUTHORIZE the payment (ordersApi.authorizePaymentForOrder)
Correction in File orders_api.dart:
Added Line 185 headers['Content-Type'] ??= 'application/json';

I don't know if this is the best fix, but for me it just works

Thanks,

**Comment by chirag729** [comment]
Fixed in 1.0.4. Thanks for the bug report.
