### ISSUE TITLE
Example++ 

### ISSUE THREAD

**Issue by underdoggit2** [Omnimind-Ltd/paypal-sdk#9]
Hi Omnimind,
Its possible to show in an example: how your PayPal Sdk buy a product xyz.
I only see create, show and update products.
I try to read the Api, but im not getting anywhere.

**Comment by chirag729** [comment]
The SDK itself doesn't not handle purchasing. You can get the HTML for a particular product/subscription you have created on the Paypal website then include that in your app in a webview. I use https://pub.dev/packages/webviewx which allows me to create a callback into my Dart code for passing back the order information which I can save to my database.

The SDK would be useful for checking the status of a purchase or checking if a subscription is still valid and has not been cancelled etc

**Comment by pardonmycode** [comment]
just asking: the author of webviewx say that has issues to use webviewx to load their auth forms/bank/paypal payment ?

**Comment by chirag729** [comment]
@pardonmycode Only the PayPal button is hosted in a webviewx view. When the user clicks the button it opens the regular OS browser for user to complete the payment so security concerns are minimal. No sensitive information is exposed in the webviewx view.

**Comment by pardonmycode** [comment]
Can you share the code of webviewx integration. I will send you a coffee.
So if the payment is done it will be registered in the database which flutter have access?

**Comment by chirag729** [comment]
@pardonmycode 

Go to https://www.paypal.com/buttons/smart and create a PayPal button. Copy the HTML code and save in a file in your assets folder to be loaded in a webviewx view. You can do something similar with subscriptions also. 


You need to edit the HTML to add your Dart callback. In the onApprove function add code to send the orderData to your Dart code via a callback function you define. Here I've created a function called PurchaseComplete
```
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (orderData) {
                    PurchaseComplete(JSON.stringify(orderData, null, 2));
                });
            },
```

In your Dart code you define your callback like this:

```
                WebViewX(
                  width: widget._responsive.shop.width,
                  height: widget._responsive.shop.webViewHeight,
                  initialContent: widget._state.payPalButtonHTML!,
                  initialSourceType: SourceType.html,
                  dartCallBacks: {
                    DartCallback(
                      name: 'PurchaseComplete',
                      callBack: (orderData) async {
                        var order = ppo.Order.fromJson(jsonDecode(orderData));
                        var purchaseUnit = order.purchaseUnits!.first;

                        var request = VerifyPurchaseRequest(
                          source: purchaseSourcePayPal,
                          productId: purchaseUnit.referenceId!,
                          transactionId: order.id!,
                          verificationData: order.id!,
                          transactionTime: DateTime.parse(order.createTime!).millisecondsSinceEpoch.toString(),
                        );

                        await widget._state.registerPurchase(request);
                      },
                    ),
                  },
                ),
```

When the user clicks the button they will be taken to the PayPal website in the the normal browser to make the purchase. When the purchase is complete you will get a callback here in your webview. You need to save the order.id to your backend at this point so you have a record of the transaction against the user who made the purchase. You can use the PayPal SDK to query the status of the order to confirm the payment went through successfully.
